### ISSUE TITLE
500 Error on Jobs & Job Configuration 

### ISSUE THREAD

**Issue by nathanuel-mills-roi** [bamotav/Hangfire.RecurringJobAdmin#102]
We are having an issue with our dashboard displaying the Hangfire information.

Both errors seem to be related to retrieving information around the Stopped Jobs, however I'm unsure about how to get this working again.

When I click on the Jobs tab at the top, I just get returned a 500-error page with the following detail:

System.NullReferenceException: Object reference not set to an instance of an object.
at Hangfire.RecurringJobAdmin.Core.JobAgent.<>c__DisplayClass4_1.<GetAllJobStopped>b__0(String jobId)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at Hangfire.RecurringJobAdmin.Core.JobAgent.GetAllJobStopped()
at Hangfire.RecurringJobAdmin.TagDashboardMetrics.<>c.<.cctor>b__1_0(RazorPage razorPage)
at Hangfire.Dashboard.Pages.InlineMetric.Execute()
at Hangfire.Dashboard.RazorPage.TransformText(String body)
at Hangfire.Dashboard.HtmlHelper.InlineMetric(DashboardMetric metric)
at Hangfire.Dashboard.Pages.SidebarMenu.Execute()
at Hangfire.Dashboard.RazorPage.TransformText(String body)
at Hangfire.Dashboard.HtmlHelper.RenderPartial(RazorPage partialPage)
at Hangfire.Dashboard.HtmlHelper.JobsSidebar()
at Hangfire.Dashboard.Pages.QueuesPage.Execute()
at Hangfire.Dashboard.RazorPage.TransformText(String body)
at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
at AutoWrapper.AutoWrapperMiddleware`1.InvokeAsync(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

I am also getting a blank page when I try and load the Job Configuration page with the following exception being thrown.

System.NullReferenceException: Object reference not set to an instance of an object.
at Hangfire.RecurringJobAdmin.Core.JobAgent.<>c__DisplayClass4_1.<GetAllJobStopped>b__0(String jobId)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at Hangfire.RecurringJobAdmin.Core.JobAgent.GetAllJobStopped()
at Hangfire.RecurringJobAdmin.Pages.GetJobDispatcher.Dispatch(DashboardContext context)
at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
at AutoWrapper.AutoWrapperMiddleware`1.InvokeAsync(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by nathanuel-mills-roi** [comment]
For anyone coming across this issue and needs the solution.

It was caused by recently deleted jobs hanging around in the `[Hangfire].[Set]` table.

I had to remove the offending jobs with the following command

`delete from Hangfire.[Set] where [Key] = 'recurring-jobs-stop' and [Value] = 'Ingest Delete Control'`
