### ISSUE TITLE
Could not resolve a service of type 'Hangfire.IRecurringJobManager'

### ISSUE THREAD

**Issue by vascofernandes** [bamotav/Hangfire.RecurringJobAdmin#27]
I am running ASP.NET Core on .NET 5 preview 1.
In Startup.cs is have this: 

````csharp
public class Startup 
{
       public void Configure(
            IApplicationBuilder app,
            IWebHostEnvironment env,
            IRecurringJobManager recurringJobs)
        {
               ....
        }
}
````
This worked fine with 0.1.5.

With the latest version (0.1.6) I get this exception. 

````csharp
> 2020-09-21 02:33:51.600 +00:00 [Critical] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception
System.Exception: Could not resolve a service of type 'Hangfire.IRecurringJobManager' for the parameter 'recurringJobs' of method 'Configure' on type 'NetProxy.Startup'.
 ---> System.BadImageFormatException: Bad IL format. The format of the file 'D:\home\site\wwwroot\api-ms-win-core-console-l1-1-0.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
   at Hangfire.RecurringJobAdmin.Core.StorageAssemblySingleton.<>c__DisplayClass7_0.<SetCurrentAssembly>b__2(String path)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Hangfire.RecurringJobAdmin.Core.StorageAssemblySingleton.SetCurrentAssembly(Assembly assembly)
   at Hangfire.RecurringJobAdmin.ConfigurationExtensions.UseRecurringJobAdmin(IGlobalConfiguration config, Assembly assembly)
   at NetProxy.Startup.<ConfigureServices>b__8_5(IGlobalConfiguration config) in /home/vsts/work/1/s/NetProxy/Startup.cs:line 164
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__0(IServiceProvider provider, IGlobalConfiguration config)
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__7(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass6_0`1.<TryAddSingletonChecked>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
````

Notice the call to Hangfire.RecurringJobAdmin.Core.StorageAssemblySingleton.SetCurrentAssembly(Assembly assembly);

**Comment by bamotav** [comment]
Hi @vascofernandes, I'll try to replicate this issue, thanks for the report it.

**Comment by vascofernandes** [comment]
Interestingly, this error only happens when I do a self-contained publishing and run the published application.

**Comment by vascofernandes** [comment]
@bamotav you can find a test repo here:

https://github.com/vascofernandes/hangfirerecurringjoberror

**Comment by bamotav** [comment]
Hi @vascofernandes thanks for sharing the link, I was trying to replicate your problem but I still have not been able to, I published your project in my local IIS and executed the job successfully but I have not gotten your error when the application loads, I will continue to trying to replicate the problem:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/36558623/94098255-3dde9180-fdf6-11ea-9658-f24f0e1b6175.png">

You can change the way you call the Trigger method, you can call it using `RecurringJob.Trigger` this is a static class and it has the` Trigger` method which you need, I don't know if your particular need is why you are injecting the interface to the Configure method:

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/36558623/94098736-46839780-fdf7-11ea-824c-5661011c764f.png">

**Comment by bamotav** [comment]
Hi @vascofernandes, I released a new version, try it and let me know.
