### ISSUE TITLE
Running into invalid class errors after upgrade to 1.6, does not occur on lower versions.

### ISSUE THREAD

**Issue by geoffreytran** [bamotav/Hangfire.RecurringJobAdmin#28]
Running into the following errors as the PeriodicJobBuilder.GetAllJobs(); method is called and it loops through all classes within the assembly looking for the recurring job attributes. Is there a way to exclude/include types that would use the attribute rather than looking at all types?

```
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. <s:Microsoft.AspNetCore.Hosting.Diagnostics>
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Hangfire.RecurringJobAdmin.PeriodicJobBuilder.GetAllJobs()
   at Hangfire.RecurringJobAdmin.ConfigurationExtensions.UseRecurringJobAdmin(IGlobalConfiguration config, Assembly assembly)
```

**Comment by bamotav** [comment]
Hi, @geoffreytran thanks for report this issue, I will fix this issue in the next release.

In the next release, I changed the way how the plugin gets all jobs by attribute.

Please wait for the next release.

**Comment by bamotav** [comment]
Hi @geoffreytran, I released a new version, try it and let me know.

**Comment by geoffreytran** [comment]
Great! thanks! I did find another issue, I'll create a new one for that.
